global_login_res:
  ifSuccess: false
  message: 登录异常，请输入验证码！
  messageCode: '-75'
  resultObject: null
global_login_res_1: 200000
global_login_res_2: 1200000
global_login_res_3: 3200000
http://www.niuinfo.com:
  http://www.niuinfo.com:
    local_login_status_code: 200
    local_login_test1: 1000200
    local_login_test2: 1800200
    local_login_test3: 3600200
